
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'mahmoud.lakhal@esprit.tn'
        headers:
            From: "Mahmoud <mahmoud.lakhal@esprit.tn>"
            X-Custom-Header: "foobar"