framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'oussama.miladi@esprit.tn'
        headers:
            From: "Oussama <oussama.miladi@esprit.tn>"
            X-Custom-Header: "foobar"